import {PERMISSIONS} from 'react-native-permissions';
import {isAndroid} from '@/utils/platform';

export const PERMISSION = {
  CAMERA_PERMISSION: isAndroid
    ? PERMISSIONS.ANDROID.CAMERA
    : PERMISSIONS.IOS.CAMERA,

  GALLERY_PERMISSION: isAndroid
    ? PERMISSIONS.ANDROID.WRITE_EXTERNAL_STORAGE
    : PERMISSIONS.IOS.PHOTO_LIBRARY,

  LOCATION_PERMISSION: isAndroid
    ? [
        PERMISSIONS.ANDROID.ACCESS_COARSE_LOCATION,
        PERMISSIONS.ANDROID.ACCESS_FINE_LOCATION,
      ]
    : [PERMISSIONS.IOS.LOCATION_WHEN_IN_USE],
};
