export const en = {
  common: {
    loading: 'Loading',
    next: 'Next',
    skip: 'Skip',
    previous: 'Previous',
    latitude: 'Latitude',
    longitude: 'Longitude',
    gender: 'Gender',
    male: 'Male',
    female: 'Female',
    other: 'Other',
    emptyData: 'No data available!',
    cancel: 'Cancel',
    yes: 'Yes',
    okay: 'Okay',
    alertTitle: 'Alert',
    saveRecordingMessage: 'Do you wish to save the Recorded audio?',
    deviceConnectionError: 'Please connect your device and try again',
    disabledAccountMessage:
      'Your account has been disabled, Please see your system administrator.',
  },
  onboarding: {
    walkthrough1Title: 'Powering ON the Stethoscope',
    walkthrough1Message:
      'Push the power button to turn the Device ON. A light will Blink when the device is Powered ON.',
    walkthrough2Title: 'Getting Started',
    walkthrough2Message:
      'Adjust the volume using the Sound Tuning Grid on the side panel of the device.',
    walkthrough3Title: 'Precise & Explicit Audio',
    walkthrough3Message:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    getStarted: 'Get Started',
  },
  login: {
    header: 'Register or Sign In',
    subHeader: 'Please enter contact no to get started',
    inputLabel: 'Contact number',
    button: 'Send OTP',
    digital: 'Digital',
    stethoscope: 'Stethoscope',
    termsOfService: 'Terms & Condition',
    privacyPolicy: 'Privacy Policy',
  },
  otpVerification: {
    header: 'Verification Code',
    subHeader: 'A 6 digit verification code has been sent to your number',
    inputLabel: 'Enter your 6 digit verification code',
    button: 'Verify',
    footerNote: "Didn't receive verification code?",
    sendAgain: 'Send Again',
  },
  updateProfile: {
    header: 'Profile',
    subHeader: 'Please complete your profile to continue',
    profileUpdate: 'Update your profile',
    button: 'Register Now',
    update: 'Update',
    firstName: 'First Name',
    firstNameHint: 'Enter your first name',
    lastName: 'Last Name',
    lastNameHint: 'Enter your last name',
    email: 'Email',
    emailHint: 'Enter your email',
    dateOfBirth: 'Date of Birth',
    dateOfBirthHint: 'Enter your Date of Birth',
    contact: 'Contact',
    contactHint: 'Enter your contact number',
    addFamilyMembers: 'Add Family Members',
    familyMembers: 'Family Members',
    addMemberHeader: 'Add Member',
    updateMemberHeader: 'Update Member',
    addMemberSubHeader: 'Please add details of your family member',
    relation: 'Relation',
    relationHint: 'Enter your relation with memeber',
    addMemberButton: 'Add Member',
    updateMemberButton: 'Update Member',
    updateMemberSubHeader: 'Please update details of your family member',
    removeMemberMessage: 'Are you sure you want to remove this member?',
    address: 'Address',
    setting: 'Setting',
  },
  addMember: {
    relationHint: 'Enter your relation with memeber',
    addFamilyMembers: 'Add more Family Members',
    familyMembers: 'Family Members',
  },
  mapScreen: {
    searchLocation: 'Search location',
  },
  home: {
    viewAll: 'View all',
    share: 'Share',
    information: 'Information',
    rename: 'Rename',
    delete: 'Delete',
    from: 'From',
    to: 'To',
  },
  profile: {
    header: 'Profile',
    logout: 'Logout',
    logoutMessage: 'Are you sure you want to logout?',
  },
  errorMessages: {
    missingPhone: 'Mobile number is missing',
    invalidPhone: 'Phone number must be valid',
    missingEmail: 'Email is missing',
    invalidEmail: 'Email address must be valid',
    invalidOTPLength: 'OTP must be at least 6 characters long',
    missingFirstName: 'First name is missing',
    missingLastName: 'Last name is missing',
    missingDateOfBirth: 'Please select date of birth',
    missingGender: 'Please select gender',
    missingRelation: 'Relation is missing',
    missingProfilePic: 'Please upload your photo',
  },
};
